### PR TITLE
Update system.prop

### PR DESCRIPTION
**Pull request by Aromer-room**

### CODE REVIEW

**Comment by emfox** [comment]
this should be accepted.
It solve the issue while switch data from SIM card 1 to SIM card 2 (sometimes cannot switch and sometimes the signal error).

**Comment by kumajaya** [comment]
I just checked https://github.com/CyanogenMod/android_frameworks_base/blob/cm-12.1/telephony/java/com/android/internal/telephony/RILConstants.java#L106 So, ro.telephony.default_network parsed as int not a comma separator value.

**Comment by emfox** [comment]
I believe for a dual sim card device, this should be two value instead of one. May be we should inplement it.
a simple search found this, http://review.cyanogenmod.org/#/c/92291/7 
hope it's useful for it.

**Comment by Aromer-room** [comment]
在6.0已经实现了这个逻辑 可以用22,22

**Comment by kumajaya** [comment]
Yes, how if we set as 22,22 or maybe 20,20 is enough https://github.com/CyanogenMod/android_frameworks_base/blob/cm-12.1/telephony/java/com/android/internal/telephony/RILConstants.java#L102

**Comment by emfox** [comment]
RedMi 2 has cdma (cdma2000/evdo?) version.

**Comment by Aromer-room** [comment]
@emfox  3Gand4G

**Comment by kumajaya** [comment]
https://github.com/kumajaya/android_device_wingtech_wt88047/commit/25dd771d553f0746dd37d251bcf5d42108a5d99a

**Pull request closed without merging**
