### PR TITLE
Solve VOIP issues in Apps

### PR DESCRIPTION
**Pull request by ghost**
This solves the Robotic sound like issue in loudspeaker in VOIP apps. Thanks to pcgg & zoneryder @xda

### CODE REVIEW

**Comment by kumajaya** [comment]
Still not sure about this patch. Please try add "audio.deep_buffer.media=true" to build.prop without this patch.

**Comment by ghost** [comment]
Tried adding that to build prop without the patch..But doesnt work, robotic sound on loudspeaker still exist...

**Comment by ghost** [comment]
It doesnt seems to break anything. Radio working fine.

**Comment by kumajaya** [comment]
Currently I have no a better solution, merged.

**Pull request closed without merging**
