### PR TITLE
wt88047: change default to -rm rf

### PR DESCRIPTION
**Pull request by niclimcy**
Normal format destroys the partition... Literally

### CODE REVIEW

**Comment by kumajaya** [comment]
Which partition will be damage by a normal format?

**Comment by niclimcy** [comment]
cache partition gets rekt and device will go into bootloop

**Comment by kumajaya** [comment]
I repeatedly reformat /cache without problem. Let me recheck it.

**Comment by niclimcy** [comment]
I think twrp somehow remembers rm-rf format if you used an older version of twrp installed

**Comment by niclimcy** [comment]
Why is it 1080x1920hq the resolution? shouldn't it be 720x1280?

**Comment by kumajaya** [comment]
This use my own Materialised TWRP repo originally for OnePlus One, runtime scaled to 720x1280.

**Comment by niclimcy** [comment]
OK! I will change it back for my source since I using original theme

**Pull request closed without merging**
