### PR TITLE
Update BoardConfig.mk

### PR DESCRIPTION
**Pull request by Aromer-room**

### CODE REVIEW

**Comment by kumajaya** [comment]
Is this applicable for Lollipop? Let me check it later.

**Comment by kumajaya** [comment]
Marshmallow branch https://github.com/kumajaya/android_device_wingtech_wt88047/commit/5e6b08943a5f51d9b323c82f16c3c7b76209b3ae

**Comment by Aromer-room** [comment]
6.0

**Comment by Aromer-room** [comment]
6.0 cm13@kumajaya

**Pull request closed without merging**
