### PR TITLE
Trick to fix Baseband

### PR DESCRIPTION
**Pull request by Aromer-room**
Trick to fix Baseband

### CODE REVIEW

**Comment by niclimcy** [comment]
Why? It's already fixed

**Comment by Aromer-room** [comment]
Baseband unknown

**Comment by Aromer-room** [comment]
存在 不显示

2015-10-07 16:51 GMT+08:00 nick37332001 notifications@github.com:

**Comment by niclimcy** [comment]
It's already fixed....... Baseband is no longer unknown

**Comment by drwatson221b** [comment]
Which build?

**Comment by niclimcy** [comment]
但是已经显示了，所以这个不用

**Comment by Aromer-room** [comment]
我这里不显示

**Pull request closed without merging**
